syn scrub; migration to config based var loading; clean for public state

diff --git a/bhq b/bhq
--- a/bhq
+++ b/bhq
@@ -8,10 +8,14 @@ _init()
 {
     #bkpath="$HOME/.local/bin/fbk"
     #export PATH="$bkpath:$PATH"
-    bkhq_d="${HOME}/.config/bkhq/"
-    bkhq_c="${HOME}/.config/bkhq.cfg"
-    declare -rg pkg_ls_dir
-    source "${bkhq_c}"
+    bkhq_d="${BHQ_DIR}"
+    bkhq_c="${BHQC}"
+    
+    [ -f ${BHQC} ] \
+        || { echo "missing bhq config; exiting"; exit; }
+
+    source ${BHQC}
+    _env_bhq
 }
 
 prnt()  { printf "BKHQ: %s\n" "#" "$1"; }
@@ -20,17 +24,20 @@ prntx() { printf "BKHQ: %s\n" "$1"; }
 _notif()
 {
     linex+=()
-    linex+=("A. dsvv sync <dssy>?\n")
-    linex+=("B. rclone 2 gdrive <min>?\n")
-    linex+=("D. dva dvb snaps\n")
+    linex+=("A. ds sync <dssy>?\n")
+    linex+=("B. rc 2 cloud <min>?\n")
+    linex+=("C. btrfs local snaps <min>?\n")
+    linex+=("X. btrfs snap 2 cloud <min>?\n")
     linex+=("\nASYNCHRONOUS VITs:\n")
-    linex+=("0. bkhq que..\n")
+    linex+=("0. dva dvb snaps\n")
+    linex+=("0. bhq que..\n")
     linex+=("1. keys \n")
     linex+=("2. logs \n")
     linex+=("\nHABITS \n")
     linex+=("X. git commits (atomised)")
-    liney=" ${linex[@]}"
-    notify-send -u low "REGULAR VITs:" "${liney}"
+    linex=" ${linex[@]}"
+    lineh+=("REGULAR VITs:")
+    notify-send -u low "${lineh}" "${linex}"
 }
 
 _bk_sys_ini()
@@ -85,7 +92,8 @@ _dev_ext_ecc_aaa() { echo "";} # todo
 # schedules
 
 _reg_aaa() {
-  _dev_lcl_vcs_xaa; }
+  _dev_lcl_vcs_xaa
+}
 
 _reg_aab()
 {
@@ -95,7 +103,6 @@ _reg_aab()
     _rem_par_min
     _notif
 }
-
 
 # selectors
 
@@ -197,8 +204,10 @@ bkls()
     done
 }
 
-index()
+main()
 {
+    cmd="${1}" && shift 1
+    init
     case ${cmd} in
         tga)      _reg_aaa;; # most regular essentialls
         tgb)      _reg_aab;;
@@ -217,13 +226,6 @@ index()
         b)        _rst_que_y gcsx ;;
         x)        que_rst_x ;;
     esac
-}
-
-main() {
-
-    cmd="${1}" && shift 1
-    init
-    index "${@}"
 }
 
 main "${@}"
diff --git a/brg b/brg
--- a/brg
+++ b/brg
@@ -3,140 +3,141 @@
 # Iarom Madden mail@iarom.org
 
 # borg wrapper
+# - [x] move some of below to config files
+#declare -g hostname="${HOST}"
 
 set -e -o pipefail
-rep="$1"
-cmd="$2"
-shift 2
 
-args=()
-opt=()
+ini()
+{
+    declare -g args=()
+    declare -g opt=()
 
-bkhq_d="${HOME}/.config/bkhq"
+    [ -f ${BHQC} ] \
+        || { echo "missing bhq config; exiting"; exit; }
 
-#todo: move some of below to config files
-
-exl_a="${bkhq_d}/exla"
-exl_b="${bkhq_d}/exlb"
-icl="${bkhq_d}/inc"
-icl_part_mid="${bkhq_d}/inc-bxx"
-icl_part_min="${bkhq_d}/inc-min"
-icl_part_mst="${bkhq_d}/inc-mst"
-
-brg_mnt="${HOME}/.local/share/aaa/mnt/xbk-brg/"
-
-hostname="${HOST}"
-
-env_dva="${bkhq_d}/env-dva"
-env_dvb="${bkhq_d}/env-dvb"
-env_dvx="${bkhq_d}/env-dvx"
-env_lca="${bkhq_d}/env-lca"
-
-src="/dat"
-
-blue=$(tput setaf 4)
-normal=$(tput sgr0)
-yellow=$(tput setaf 3)
+    source ${BHQC}
+    _env_bhq
+}
 
 prn_l()     { printf "\n"; }
 
-prn_h()     { printf "BRG: %s \n" "################################" "${1}"; }
+prn_h()     { printf "BRG: %s \n" " " "${1}"; }
 
-prn()        { printf "BRG: %s \n" "${1}"; }
+prn()       { printf "BRG: %s \n" "${1}"; }
 
 prn_args()
 {
-    prn_l
-    prn "${1}"
+    prn_l; prn_l
+    prn "borg"
     shift 1
-    printf "BRG:   %s \n" "${@}"
+    printf "BRG:   %s \n" ${args[@]}${YELLOW}
     prn_l
 }
 
 env_set()
 {
-    . ${1}
-    prn_l
-    prn "${2}: ${BORG_REPO} {${BORG_PASSCOMMAND}}"
+    ${1}
+    prn_l; prn "${BHQ_DEV}: ${BORG_REPO} {${BORG_PASSCOMMAND}}"
 }
 
 env_set_rem()
 {
     # todo
-    nm_mobile && exit 1
-    env_set "${1}" "${2}"
+    nm_mobile && exit 1 #todo: exit function printing message
+    env_set "${1}"
 }
 
-case "${rep}" in
-    dva) env_set ${env_dva} "device_a" ;;
-    dvb) env_set ${env_dvb} "device_b" ;;
-    dvx) env_set ${env_dvx} "device_x" ;;
-    lca) prn "lca: TODO" && exit
-            env_set ${env_lca} "local_a" ;;
-    was.a) prn "was.a is TODO \n" && exit
-            env_set_rem ${rem_was} "wasabi_a" ;;
-    *) prn "repo required" && exit
-esac
+brg_cmd() { exec borg "${args[@]}"; }
 
-case ${cmd} in
+set_rep()
+{
+    case "${rep}" in
+        dva)  env_set "_env_dva"  ;;
+        dvb)  env_set "_env_dvb"  ;;
+        dvx)  env_set "_env_dvx"  ;;
+        lca)  env_set "_env_lca"  ;;
+        wasa) env_set "_env_r_wia" ;;
+        wasb) env_set "_rem_r_wib" ;;
+        *)    prn "repo required" && exit
+    esac
+}
+
+set_cmd()
+{
+    case ${cmd} in
     xx|custom)
-        prn "choose a custom command.." ""
+        prn "custom command: ${@}" ""
         args+=( "${@}" )
         ;;
 
     in|init)
         prn "init" ""
-        args+=( 'init')
-        args+=( '--encryption' 'repokey-blake2')
+        args+=( 'init' )
+        args+=( '--encryption' 'repokey-blake2' )
         args+=( "${@}" )
         ;;
 
     mn|mount|mnt|m)
-        prn "mount: ${brg_mnt}" ""
-        args+=('mount')
-        args+=("${BORG_REPO}")
-        args+=("${brg_mnt}")
+        prn "mount: ${BORG_MOUNTPOINT}" ""
+        args+=( 'mount' )
+        args+=( "${BORG_REPO}" )
+        args+=( "${BORG_MOUNTPOINT}" )
         ;;
 
     un|umount|umnt)
-        prn "umount: ${brg_mnt}" ""
-        args+=('umount')
-        args+=("${brg_mnt}")
+        prn "umount: ${BORG_MOUNTPOINT}" ""
+        args+=( 'umount' )
+        args+=( "${BORG_MOUNTPOINT}" )
         ;;
 
     bf|backup-full|full)
-        prn "src: full '$src/'" \
-            "exl: ${exl_a}:" \
+        prn "src: full '${SRC}/'" \
+            "exl: ${BHQ_EXL_AAX}:" \
             ""
         args+=( 'create' )
         args+=( '--stats' )
         args+=( '--progress' )
-        args+=( "--exclude-from" "$exl_a")
+        args+=( "--exclude-from" "${BHQ_EXL_AAX}" )
         args+=( "::'$(date +%y.%m.%d.%H.%M)'" )
-        args+=( "$src/" )
+        args+=( "${SRC}/" )
         args+=( "${@}"     )
         ;;
 
     bm|backup-mid|bk-mid)
-        prn "src: partial.mid '$src/'" "exl: ${exl_a} & ${exl_b}:"
+        prn "src: partial.mid '${SRC}/'" \
+            "exl: ${BHQ_EXL_AAX}"
+            "exl: ${BHQ_EXL_ABX}"
         args+=( 'create' )
         args+=( '--stats' )
         args+=( '--progress' )
-        args+=( "--exclude-from"    "$exl_b")
-        args+=( "--exclude-from"    "$exl_a")
+        args+=( "--exclude-from" "${BHQ_EXL_AAX}" )
+        args+=( "--exclude-from" "${BHQ_EXL_ABX}" )
         args+=( "::'$(date +%y.%m.%d.%H.%M)'" )
-        args+=( "$src/" )
-        args+=( "${@}"     )
+        args+=( "${SRC}/" )
+        args+=( "${@}" )
         ;;
   
-    part) #"Partial Home Backup # TODO
+    part)
+        #"Partial Home Backup # TODO
         ;;
 
-    *) prn "no cmd" && exit ;;
-esac
+    *) prn "no cmd" && exit
+        ;;
 
-prn_l
+    esac
+}
 
-prn_args "borg" "${args[@]}${yellow}"
+main()
+{
+    rep="${1}"; cmd="${2}"; shift 2
+    ini
 
-borg "${args[@]}"
+    set_rep
+    set_cmd "${@}"
+
+    prn_args
+    brg_cmd
+}
+
+main "${@}"
diff --git a/kys b/kys
--- a/kys
+++ b/kys
@@ -2,77 +2,82 @@
 
 # iarom madden mail@iarom.org
 
-rep=${1}
-cmd=${2}
-shift 2
+ini_v()
+{
+    rep=${1}
+    cmd=${2}
+    shift 2   
+    
+    [ -f ${BHQC} ] \
+        || { echo "missing bhq config; exiting"; exit; }
 
-gpg_dir="$HOME/.local/share/gnupg"
-bkhq_c="$HOME/.config/bkhq"
+    source ${BHQC}
+    _env_bhq
+}
 
-prnt_h1() { printf "KY: %s\n" " " "########################" "$1"; }
+prnt_h1() { printf "KY: %s\n" " " "##" "${1}"; }
 
-prnt_h2() { printf "KY: %s\n" "----------------------" "$1"; }
+prnt_h2() { printf "KY: %s\n" "--" "${1}"; }
 
-prnt()    { printf "KY: %s\n" "$1"; }
+prnt()    { printf "KY: %s\n" "${1}"; }
 
 prnt_ln() { printf "\n"; }
-
-env_dva="$bkhq_c/env.dva"
-env_dvb="$bkhq_c/env.dvb"
-env_dvc="$bkhq_c/env.dvc"
-env_dua="$bkhq_c/env.dua"
-env_dub="$bkhq_c/env.dub"
-env_duc="$bkhq_c/env.duc"
 
 mkgpg()
 {
     prnt "no gpg dir, creating it..."
     gpgconf --kill gpg-agent
-    mkdir "$gpg_dir"
-    ln -s $gpg_dir $HOME/.gnupg
-    chmod 700 "$gpg_dir"
+    mkdir "${GNUPGHOME}"
+    ln -s "${GNUPGHOME}" $HOME/.gnupg
+    chmod 700 "${GNUPGHOME}"
 }
 
-[ "$rep" ] || { prnt "no repo provided"; exit; }
+ini()
+{
+    [ "${rep}" ] || { prnt "no repo provided"; exit; }
 
-[ "$cmd" ] || { prnt "no cmd provided"; exit; }
+    [ "${cmd}" ] || { prnt "no cmd provided"; exit; }
 
-prnt_h1 "init ky sciprt..."
+    prnt_h1 "init kys script..."
 
-[ -d "$gpg_dir" ] || mkgpg
+    [ -d "${GNUPGHOME}" ] || mkgpg
+}
 
-env_set()     { . $1 && prnt_h1 "$2: $KY_REPO"; }
+env_set()     { . $1 && prnt_h1 "${BHQ_DEV}: ${KY_REPO}"; }
 
-case ${rep} in
-    dva) env_set $env_dva "dva" ;;
-    dvb) env_set $env_dvb "dvb" ;;
-    dvc) env_set $env_dvc "dvc" ;;
+set_rep()
+{
+    case ${rep} in
+    dva) env_set env_dva ;;
+    dvb) env_set env_dvb ;;
+    dvc) env_set env_dvc ;;
     #dvd) KY_REPO="$mnt_x/dvd/.key" ;;
-    dua) env_set $env_dua "dua" ;;
-    dub) env_set $env_dub "dub" ;;
-    duc) env_set $env_duc "duc" ;;
+    #dua) env_set env_dua ;;
+    #dub) env_set env_dub ;;
+    #duc) env_set env_duc ;;
     #rma) KY_REPO="$HOME/.config/key" ;; # remoe a : todo: systemitise using shamir's algorithm
-esac
+    esac
+}
 
 # bk exp
 
-gpg_bk_init()  { mkdir -p $KY_REPO; chmod 700 "$KY_REPO"; }
+gpg_bk_init()  { mkdir -p ${KY_REPO}; chmod 700 "${KY_REPO}"; }
 
 gpg_bk_pub()
 {
     gpg --export --armor --export-options backup \
-        --output "$KY_REPO/pubkeys.asc"
+        --output "${KY_REPO}/pubkeys.asc"
 }
 
 gpg_bk_prv()
 {
     gpg --export-secret-keys --armor --export-options backup \
-        --output "$KY_REPO/privatekeys.asc"
+        --output "${KY_REPO}/privatekeys.asc"
 }
 
-gpg_bk_trust() { gpg --export-ownertrust > "$KY_REPO/ownertrust.txt"; }
+gpg_bk_trust() { gpg --export-ownertrust > "${KY_REPO}/ownertrust.txt"; }
 
-gpg_ls_bk()    { ls -al "$KY_REPO/"; }
+gpg_ls_bk()    { ls -al "${KY_REPO}/"; }
 
 gpg_bk()
 {
@@ -88,13 +93,13 @@ gpg_bk()
 gpg_imp_pub()
 {
     prnt_h2 "importing Public Keys"
-    gpg --import --import-options restore "$KY_REPO/pubkeys.asc"
+    gpg --import --import-options restore "${KY_REPO}/pubkeys.asc"
 }
 
 gpg_imp_priv()
 {
     prnt_h2 "importing Private Keys"
-    gpg --import --import-options restore "$KY_REPO/privatekeys.asc"
+    gpg --import --import-options restore "${KY_REPO}/privatekeys.asc"
 }
 
 gpg_imp_test()
@@ -109,7 +114,7 @@ gpg_imp_test()
 gpg_imp_trust()
 {
     prnt_h2 "importing ownertrust"
-    gpg --import-ownertrust --import-options restore $KY_REPO/ownertrust.txt
+    gpg --import-ownertrust --import-options restore ${KY_REPO}/ownertrust.txt
 }
     
 gpg_imp_finish()
@@ -130,9 +135,18 @@ gpg_imp()
     gpg_imp_finish
 }
 
-case ${cmd} in
+main()
+{
+    ini_v ${@}
+    ini
+    set_rep
+    
+    case ${cmd} in
     exp|bk|bkp)    gpg_bk ;;
     imp)           gpg_imp ;;
-esac
+    esac
 
-prnt_ln
+    prnt_ln
+}
+
+main "${@}"
